name: spadesegresnet
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - pillow=9.3.0
  - python=3.8.5
  - pip:
    - h5py==3.8.0
    - imageio==2.25.0
    - imutils==0.5.4
    - matplotlib==3.6.3
    - opencv-python==4.7.0.68
    - opencv-python-headless==4.7.0.68
    - pytorch-lightning==1.0.8
    - scanpy==1.9.3
    - scikit-image==0.19.3
    - scikit-learn==1.3.1
    - scipy==1.10.0
    - seaborn==0.12.2
    - tabulate==0.9.0
    - torch==2.0.0+cu117
    - torch-fidelity==0.3.0
    - torchsummary==1.5.1
    - tqdm==4.64.1
